// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAQ91O1NptCn_k4SYrhGXxGlkJ_mSz4co',
    appId: '1:164963028920:web:3a4f1945d5eba129b6094d',
    messagingSenderId: '164963028920',
    projectId: 'shivila-f8bfe',
    authDomain: 'shivila-f8bfe.firebaseapp.com',
    storageBucket: 'shivila-f8bfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvE80LAsYnPBW0E7xispyWBANhLpkXmwM',
    appId: '1:164963028920:android:dacb41cb02f51784b6094d',
    messagingSenderId: '164963028920',
    projectId: 'shivila-f8bfe',
    storageBucket: 'shivila-f8bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSG47e_LK78ywiCRdNHa-B4WBBTAX2uc',
    appId: '1:164963028920:ios:dbf0f1d36e479ef6b6094d',
    messagingSenderId: '164963028920',
    projectId: 'shivila-f8bfe',
    storageBucket: 'shivila-f8bfe.appspot.com',
    iosBundleId: 'com.example.shivila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXSG47e_LK78ywiCRdNHa-B4WBBTAX2uc',
    appId: '1:164963028920:ios:3384122c70f1acd8b6094d',
    messagingSenderId: '164963028920',
    projectId: 'shivila-f8bfe',
    storageBucket: 'shivila-f8bfe.appspot.com',
    iosBundleId: 'com.example.shivila.RunnerTests',
  );
}
